site_name: 5 sterren-model voor transparante algoritmes
theme:
  name: material
  font: 
    text: Karla
  palette: 
    primary: teal
  features: 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.sections.expand
    - toc.integrate
    - navigation.indexes
  logo: img/5 sterrenmodel voor.svg
  favicon: img/5sterren-geel.svg
  language: nl
nav:
  - Home: index.md
  - Whitepaper: whitepaper.md
  - Model: model.md
  - Nieuws:
    - blog/index.md
  - Over 5 sterren: about.md
markdown_extensions:
  - attr_list
plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
      categories_toc: true
      categories: true
      post_dir: "blog/posts"
      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      archive: false
