site_name: 5 sterren-model voor transparante algoritmes
theme:
  name: material
  font: 
    text: Karla
  palette: 
    primary: teal
  features: 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.sections.expand
    - toc.integrate
nav:
  - Home: index.md
  - Model: model.md
  - Whitepaper: whitepaper.md
  - Community:


  
