site_name: 5 sterren-model voor transparante algoritmes
theme:
  name: material
  font: 
    text: Karla
  palette: 
    primary: teal
  features: 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.sections.expand
    - toc.integrate
  logo: img/5 sterrenmodel voor.svg
nav:
  - Home: index.md
  - Whitepaper: whitepaper.md
  - Model: model.md
  - Nieuws: news.md
  - Over 5 sterren: about.md
markdown_extensions:
  - attr_list
